In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [14]:
df  = pd.read_excel("Book.xlsx")
df

area    price
0   2600  550000
1   3000  565000
2   3200  610000
3   3600  680000
4   4000  725000

In [16]:
new_df = df.drop('price',axis='columns')
new_df

area 
0   2600
1   3000
2   3200
3   3600
4   4000

In [22]:
model = linear_model.LinearRegression()
model.fit(new_df, df.price)

LinearRegression()

In [23]:
model.predict([[5000]])

C:\Users\Ayush\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [24]:
model.coef_

array([135.78767123])

In [25]:
model.intercept_

180616.43835616432

In [27]:
# y = m*x + b
# where m = slope , x = variable , b = intercept 
135.78767123*5000+180616.43835616432

859554.7945061643

In [29]:
area_df = pd.read_csv("books.csv")
area_df

area 
0    1000
1    1500
2    2300
3    3540
4    4120
5    5490
6    3460
7    4750
8    2300
9    9000
10   8600
11   7100

In [30]:
p=model.predict(area_df)

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  926090.75342466,
        650441.78082192,  825607.87671233,  492928.08219178,
       1402705.47945205, 1348390.4109589 , 1144708.90410959])

In [41]:
area_df['prices']=p
area_df

NameError: name 'p' is not defined